# Generated by Django 6.1 on 2026-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.CharField(verbose_name='Описание')),
                ('price', models.IntegerField(help_text='Если цена обсуждается с клиентом отдельно, то оставьте поле пустым', null=True, verbose_name='Цена')),
                ('include_in_work', models.CharField(help_text='Вводите то, что включено в работу через запятую с пробелом для точного отображения информации на сайте(ровно 3 пункта для правильности отображения).', verbose_name='Включено в работу')),
                ('result', models.CharField(help_text='Введите то, что будет результатом работы.', verbose_name='Результат работы')),
                ('what_need', models.CharField(help_text='Введите то, что потребуется от клиента в ходе выполнения работы, например название или описание его требования(ровно 3 пункта для правильности отображения, также через запятую с пробелом).', verbose_name='Что требуется от клиента')),
                ('date', models.CharField(help_text='Писать в кол времени, неделя, день и тд, в случае, если дедлайн обсуждается с клиентом отдельно - оставить поле пустым.', null=True, verbose_name='Дедлайны выполнения работы')),
            ],
        ),
    ]
