# Generated by Django 6.1 on 2026-09-06 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.CharField(blank=True, help_text='Писать в кол времени, неделя, день и тд, в случае, если дедлайн обсуждается с клиентом отдельно - оставить поле пустым.', null=True, verbose_name='Дедлайны выполнения работы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, help_text='Если цена обсуждается с клиентом отдельно, то оставьте поле пустым', null=True, verbose_name='Цена'),
        ),
    ]
